#!/usr/bin/env python3
"""The Living Past — organism production queue / tracking board (#18).

Ties the roster, the sizing, the prompt, and the placement anchor into ONE board so the
32-organism build can be handed to a cheap executor (subagent) and ground out batch by batch.
Emits:
  * living_past/build_queue.json  — machine board (status per organism, preserved across runs)
  * living_past/BUILD_QUEUE.md     — readable board grouped by stratum

Status lifecycle:  queued → generated → isolated → placed → approved
The executor advances status; the human/Fable gate flips `placed → approved` (or back to queued).

    python3 tools/build_queue.py            # (re)build the board, preserving status
    python3 tools/build_queue.py --reset    # wipe status back to 'queued'
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from lp_organism_prompt import build_prompt, AR_HINT          # noqa: E402
from scale_calc import compute_size                            # noqa: E402
from compose_organism import SECTION_ANCHOR, ID_ANCHOR, PROOF_W, MASTER_W  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
LP = ROOT / "living_past"
VOL = json.loads((LP / "volume_v.json").read_text())
JSON_OUT = LP / "build_queue.json"
MD_OUT = LP / "BUILD_QUEUE.md"
STRATA = [("above", "Above Ground"), ("underground", "Underground"),
          ("shoreline", "Shoreline"), ("ocean", "Ocean")]


def anchor_for(o: dict) -> dict:
    return {**SECTION_ANCHOR.get(o.get("section", "above"), {}), **ID_ANCHOR.get(o["id"], {})}


def row(o: dict) -> dict:
    sz = compute_size(o.get("size", ""))
    master_px = round(sz.parsed_m * 270) if sz.parsed_m else None
    proof_px = round(master_px * PROOF_W / MASTER_W) if master_px else None
    a = anchor_for(o)
    return {
        "id": o["id"],
        "commonName": o.get("commonName", ""),
        "section": o.get("section", ""),
        "position": o.get("position", 0),
        "size": o.get("size", ""),
        "draw_px_master": master_px,
        "draw_px_proof": proof_px,
        "ar": AR_HINT.get(o.get("type", ""), "3:2"),
        "anchor": {"x": a.get("x"), "y": a.get("y"), "kind": a.get("anchor")},
        "prompt": build_prompt(o),
        "status": "queued",
        "notes": "",
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Build the Living Past organism production queue")
    ap.add_argument("--reset", action="store_true", help="reset all status to 'queued'")
    args = ap.parse_args(argv)

    prev = {}
    if JSON_OUT.exists() and not args.reset:
        prev = {r["id"]: r for r in json.loads(JSON_OUT.read_text())["organisms"]}

    rows = []
    for o in VOL["organisms"]:
        r = row(o)
        if o["id"] in prev:                       # preserve human-advanced status + notes
            r["status"] = prev[o["id"]].get("status", "queued")
            r["notes"] = prev[o["id"]].get("notes", "")
        rows.append(r)

    JSON_OUT.write_text(json.dumps({"volume": VOL["$meta"]["volume"], "organisms": rows},
                                   indent=2, ensure_ascii=False) + "\n")

    # readable board
    counts = {}
    for r in rows:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    lines = ["# The Living Past · Vol V — Build Queue",
             "",
             f"*Generated by `tools/build_queue.py` from `volume_v.json`. "
             f"{len(rows)} organisms · status: "
             + " · ".join(f"{k} {v}" for k, v in sorted(counts.items())) + "*",
             "",
             "Status: `queued → generated → isolated → placed → approved`  "
             "(executor advances; gate flips `placed→approved`).",
             ""]
    for sec, label in STRATA:
        grp = sorted([r for r in rows if r["section"] == sec], key=lambda x: x["position"])
        if not grp:
            continue
        lines.append(f"## {label}")
        lines.append("")
        lines.append("| # | ID | Species | Size | Draw px (master) | AR | Status |")
        lines.append("|---|----|---------|------|------------------|----|--------|")
        for r in grp:
            dp = r["draw_px_master"] or "—"
            lines.append(f"| {r['position']:02d} | {r['id']} | {r['commonName']} | "
                         f"{r['size']} | {dp} | {r['ar']} | {r['status']} |")
        lines.append("")
    MD_OUT.write_text("\n".join(lines))
    print(f"wrote {JSON_OUT.name} + {MD_OUT.name}: {len(rows)} organisms  ({counts})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
